import { z } from 'zod'

export const fetchItemReturnSchema = z.object({
  value: z.string().min(1),
  label: z.string().min(1),
})
export const fetchItemsReturnSchema = z.array(fetchItemReturnSchema)
export type fetchItemsReturn = z.infer<typeof fetchItemsReturnSchema>
export type fetchItemReturn = z.infer<typeof fetchItemReturnSchema>

const configSchema = z.object({
  customFields: z.object({
    name: z.string().min(1),
    description: z.string().min(1).optional(),
    icon: z.union([
      z.literal('Alien'),
      z.literal('Archive'),
      z.literal('ArrowClockwise'),
      z.literal('ArrowDown'),
      z.literal('ArrowLeft'),
      z.literal('ArrowLineLeft'),
      z.literal('ArrowLineRight'),
      z.literal('ArrowRight'),
      z.literal('ArrowUp'),
      z.literal('ArrowsCounterClockwise'),
      z.literal('ArrowsOut'),
      z.literal('Bell'),
      z.literal('Bold'),
      z.literal('Book'),
      z.literal('Briefcase'),
      z.literal('BulletList'),
      z.literal('Calendar'),
      z.literal('Car'),
      z.literal('CaretDown'),
      z.literal('CaretUp'),
      z.literal('Cast'),
      z.literal('CastleTurret'),
      z.literal('ChartBubble'),
      z.literal('ChartCircle'),
      z.literal('ChartPie'),
      z.literal('Check'),
      z.literal('CheckCircle'),
      z.literal('CheckCircleEmpty'),
      z.literal('ChevronDown'),
      z.literal('ChevronLeft'),
      z.literal('ChevronRight'),
      z.literal('ChevronUp'),
      z.literal('Clock'),
      z.literal('ClockCounterClockwise'),
      z.literal('Cloud'),
      z.literal('CloudUpload'),
      z.literal('Code'),
      z.literal('CodeBlock'),
      z.literal('Coffee'),
      z.literal('Cog'),
      z.literal('Collapse'),
      z.literal('Command'),
      z.literal('Crop'),
      z.literal('Cross'),
      z.literal('CrossCircle'),
      z.literal('Crown'),
      z.literal('Cursor'),
      z.literal('Database'),
      z.literal('Discuss'),
      z.literal('Download'),
      z.literal('Drag'),
      z.literal('Duplicate'),
      z.literal('Earth'),
      z.literal('EarthStriked'),
      z.literal('EmotionHappy'),
      z.literal('EmotionUnhappy'),
      z.literal('Expand'),
      z.literal('ExternalLink'),
      z.literal('Eye'),
      z.literal('EyeStriked'),
      z.literal('Faders'),
      z.literal('Feather'),
      z.literal('File'),
      z.literal('FileCsv'),
      z.literal('FileError'),
      z.literal('FilePdf'),
      z.literal('FileXls'),
      z.literal('FileZip'),
      z.literal('Filter'),
      z.literal('Folder'),
      z.literal('Gift'),
      z.literal('Globe'),
      z.literal('GraphQl'),
      z.literal('GridFour'),
      z.literal('GridNine'),
      z.literal('HandHeart'),
      z.literal('Hashtag'),
      z.literal('HeadingFive'),
      z.literal('HeadingFour'),
      z.literal('HeadingOne'),
      z.literal('HeadingSix'),
      z.literal('HeadingThree'),
      z.literal('HeadingTwo'),
      z.literal('Headphones'),
      z.literal('Heart'),
      z.literal('House'),
      z.literal('Image'),
      z.literal('Images'),
      z.literal('IndentDecrease'),
      z.literal('IndentIncrease'),
      z.literal('Information'),
      z.literal('Italic'),
      z.literal('Key'),
      z.literal('Layout'),
      z.literal('Lightbulb'),
      z.literal('Lightning'),
      z.literal('Link'),
      z.literal('List'),
      z.literal('ListPlus'),
      z.literal('ListSearch'),
      z.literal('Loader'),
      z.literal('Lock'),
      z.literal('Magic'),
      z.literal('Mail'),
      z.literal('ManyToMany'),
      z.literal('ManyToOne'),
      z.literal('ManyWays'),
      z.literal('Message'),
      z.literal('Microphone'),
      z.literal('Minus'),
      z.literal('MinusCircle'),
      z.literal('Monitor'),
      z.literal('Moon'),
      z.literal('More'),
      z.literal('Move'),
      z.literal('MusicNotes'),
      z.literal('NumberList'),
      z.literal('OneToMany'),
      z.literal('OneToOne'),
      z.literal('OneWay'),
      z.literal('PaintBrush'),
      z.literal('PaintRoller'),
      z.literal('Palette'),
      z.literal('PaperPlane'),
      z.literal('Paperclip'),
      z.literal('Paragraph'),
      z.literal('Pencil'),
      z.literal('Phone'),
      z.literal('Pin'),
      z.literal('PinMap'),
      z.literal('Plane'),
      z.literal('Plant'),
      z.literal('Play'),
      z.literal('Plus'),
      z.literal('PlusCircle'),
      z.literal('PresentationChart'),
      z.literal('PriceTag'),
      z.literal('PuzzlePiece'),
      z.literal('Question'),
      z.literal('Quotes'),
      z.literal('Restaurant'),
      z.literal('Rocket'),
      z.literal('Scissors'),
      z.literal('SealCheck'),
      z.literal('Search'),
      z.literal('Server'),
      z.literal('Shield'),
      z.literal('Shirt'),
      z.literal('ShoppingCart'),
      z.literal('SignOut'),
      z.literal('SlidersHorizontal'),
      z.literal('Sparkle'),
      z.literal('SquaresFour'),
      z.literal('Stack'),
      z.literal('Star'),
      z.literal('Stethoscope'),
      z.literal('Stop'),
      z.literal('Store'),
      z.literal('StrikeThrough'),
      z.literal('Sun'),
      z.literal('Television'),
      z.literal('ThumbDown'),
      z.literal('ThumbUp'),
      z.literal('Train'),
      z.literal('Trash'),
      z.literal('Typhoon'),
      z.literal('Underline'),
      z.literal('Upload'),
      z.literal('User'),
      z.literal('VolumeMute'),
      z.literal('VolumeUp'),
      z.literal('Walk'),
      z.literal('WarningCircle'),
      z.literal('Wheelchair'),
    ]).optional(),
    inputSize: z.object({
      default: z.union([z.literal(4), z.literal(6), z.literal(8), z.literal(12)]),
      isResizable: z.boolean(),
    }).optional(),
    fetchItems: z.function().args(z.string()).returns(z.union([fetchItemsReturnSchema, z.promise(fetchItemsReturnSchema)])),
    fetchItem: z.function().args(z.string()).returns(z.union([fetchItemReturnSchema, z.promise(fetchItemReturnSchema)])),
  }).array(),
})

export type Config = z.infer<typeof configSchema>

export default {
  default: {
    customFields: [],
  } satisfies Config,
  validator(config: unknown) {
    configSchema.parse(config)
  },
}
